### ISSUE TITLE
FreeBSD: error on 'service' hook: No service system detected.

### ISSUE THREAD

**Issue by ghost** [bruhs/caddy-service#7] opened 2017-06-15 14:57 UTC
Caddy shuts down after printing `error on 'service' hook: No service system detected.` to the log

**Comment by hacdias** [comment] 2017-06-15 21:19
Hello @voltagex! Sorry for that. It is related to the library we're relying on. Please open an issue at [kardianos/service's issues](https://github.com/kardianos/service/issues) and link it to this issue 😄

**Comment by ghost** [comment] 2017-06-16 04:34
Done, do you want me to close this issue?

**Comment by hacdias** [comment] 2017-06-16 20:37
Thanks for opening the issue! I'll leave this open until the problem is solved.

**Comment by hacdias** [comment] 2020-07-17 18:33
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.

**Closed as completed by hacdias** 2020-07-17 18:33 UTC
