### ISSUE TITLE
-agree makes service unable to start

### ISSUE THREAD

**Issue by mrexodia** [bruhs/caddy-service#19] opened 2018-04-06 17:22 UTC
Reproduction steps:

Install the service:
```
sudo caddy -service install -conf /home/user/Caddyfile -email user@example.com -agree -log /var/log/caddy.log
```

Try to start the service:
```
sudo service Caddy start
```

Service status:
```
 sudo service Caddy status
● Caddy.service - Caddy's service
   Loaded: loaded (/etc/systemd/system/Caddy.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2018-04-06 17:14:22 UTC; 2s ago
  Process: 9481 ExecStart=/usr/local/bin/caddy -agree true -conf /home/user/Caddyfile -email user@example.com -log /var/log/caddy.log (code=exited, status=1/FAILURE)
 Main PID: 9481 (code=exited, status=1/FAILURE)
```

When running the `ExecStart` command by hand you get:
```
args:2 - Error during parsing: Unknown directive 'true'
```

It's easy to fix by hand by editing the `ExecStart` key in `/etc/systemd/system/Caddy.service` but a slight annoyance.

**Comment by fabiofcferreira** [comment] 2018-04-08 04:29
Hi there,

I've been looking at this issue and I've concluded that this error message is caused by Caddy itself. Caddy, unlike any other flags is using `-agree=true` syntax for the flag in question.
Thus, I highly recommend sticking with the editing `ExecStart` key option because it's a 1-time task, has no interference with the Caddy's performance and is the fastest and probably the best solution for now.

This way you'll be able to run everything smoothly until any changes are made to Caddy source.

Thanks for using our plugin! :+1

**Comment by fabiofcferreira** [comment] 2018-04-08 18:24
Hey there @mrexodia!

Sorry for closing the issue. I've successfully found the solution for the problem you're experiencing, which I've pushed a few moments ago(https://github.com/hacdias/caddy-service/commit/2b51934d789299da6e306ed4a059cd30fd4ad02d).

Sorry again for closing this issue and I hope that I've solved it too.
Please comment back if you have any further issues with my new solution.

Thanks 👍

**Comment by fabiofcferreira** [comment] 2018-04-08 19:39
Hey again,

The deployment of our plugin has failed due to a conflict with Cloudflare which is preventing plugins from being deployed. Also, after talking with Matt from Caddy we now know that we might have to wait a week or so for the new Caddy release. Until we can deploy caddy-service and you have tried the new code we will keep the issue open.

**Comment by mrexodia** [comment] 2018-04-08 21:34
Hi,

That's alright @fabiofcferreira I fixed the issue on my end, this was just in case someone ran into the same issue :+1: Good to know it's fixed now though!

Thanks,

Duncan

**Closed as completed** 2018-12-31 16:23 UTC
